
@server = http://localhost:4004


###
POST {{server}}/export-pdf/format_PDF
Content-Type: application/json

{
   "results":[
       {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003126",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"MRSH073_000_ECMLT",
         "REFERENCE_MATERIAL":"GERBER BORDER SS SHIRT",
         "MATERIAL_ID":"MRSH073_000_ECMLT_L-XL",
         "MATERIAL":"GERBER BORDER SS SHIRT, L-XL M IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1091",
         "BRAND":"BODE",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"MAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/MRSH073_000_ECMLT.jpg",
         "BUSINESSPARTNERID":"C002669",
         "BUSINESSPARTNER":"JOSE LUIS VINAS MORA",
         "BUSINESSPARTNEREMAIL":"luis.mora1968@yahoo.com",
         "DOCUMENTPOSSALESPERSONID":"50010",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"250.95",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"438.9",
         "SELL_OUT_PRICE":"438.9",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"KARIM BENDADDA",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003126",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"MRSH102_000_BLACK",
         "REFERENCE_MATERIAL":"GEO LACE OVERSHIRT",
         "MATERIAL_ID":"MRSH102_000_BLACK_M-L",
         "MATERIAL":"GEO LACE OVERSHIRT, M-L M IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1091",
         "BRAND":"BODE",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"MAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/MRSH102_000_BLACK.jpg",
         "BUSINESSPARTNERID":"C002669",
         "BUSINESSPARTNER":"JOSE LUIS VINAS MORA",
         "BUSINESSPARTNEREMAIL":"luis.mora1968@yahoo.com",
         "DOCUMENTPOSSALESPERSONID":"50010",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"286.65",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"501.9",
         "SELL_OUT_PRICE":"501.9",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"KARIM BENDADDA",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003127",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"223SW014_2133_130",
         "REFERENCE_MATERIAL":"LE HAUT DE MAILLOT SIGNATU",
         "MATERIAL_ID":"223SW014_2133_130_XS",
         "MATERIAL":"LE HAUT DE MAILLOT SIGNATU, XS W IN",
         "SKU_SEASON":"FW23",
         "BRAND_ID":"1275",
         "BRAND":"JACQUEMUS",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/223SW014_2133_130.jpg",
         "BUSINESSPARTNERID":null,
         "BUSINESSPARTNER":null,
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50015",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"60",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"145",
         "SELL_OUT_PRICE":"145",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"LISA FROGER",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003127",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"223SW025_2133_130",
         "REFERENCE_MATERIAL":"LE BAS DE MAILLOT SIGNATU",
         "MATERIAL_ID":"223SW025_2133_130_XXS",
         "MATERIAL":"LE BAS DE MAILLOT SIGNATU, XXS W IN",
         "SKU_SEASON":"FW23",
         "BRAND_ID":"1275",
         "BRAND":"JACQUEMUS",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/223SW025_2133_130.jpg",
         "BUSINESSPARTNERID":null,
         "BUSINESSPARTNER":null,
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50015",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"55",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"120",
         "SELL_OUT_PRICE":"120",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"LISA FROGER",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003127",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"231BA051_3066_180",
         "REFERENCE_MATERIAL":"BAMBINO LONG FICIU",
         "MATERIAL_ID":"231BA051_3066_180_OS",
         "MATERIAL":"BAMBINO LONG FICIU, ONE SIZE",
         "SKU_SEASON":"FW23",
         "BRAND_ID":"1275",
         "BRAND":"JACQUEMUS",
         "FAMILY_ID":"BAG",
         "FAMILY":"BAGS",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/231BA051_3066_180.jpg",
         "BUSINESSPARTNERID":null,
         "BUSINESSPARTNER":null,
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50015",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"365",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"890",
         "SELL_OUT_PRICE":"890",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"LISA FROGER",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003128",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"4DC2234505_000_401",
         "REFERENCE_MATERIAL":"WIDE JEAN CRYSTAL CUFF",
         "MATERIAL_ID":"4DC2234505_000_401_27",
         "MATERIAL":"WIDE JEAN CRYSTAL CUFF, 27 W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1530",
         "BRAND":"T BY ALEXANDER WANG",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/4DC2234505_000_401.jpg",
         "BUSINESSPARTNERID":"C002652",
         "BUSINESSPARTNER":"LIORA EPELSTEIN",
         "BUSINESSPARTNEREMAIL":"lioraepelsteinm@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50011",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"366.45",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"658",
         "SELL_OUT_PRICE":"658",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"HELENE GIAMI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003128",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"LWYA026S23_DEN001_4584",
         "REFERENCE_MATERIAL":"OVER THE RAINBOW DENIM PANTS",
         "MATERIAL_ID":"LWYA026S23_DEN001_4584_25",
         "MATERIAL":"OVER THE RAINBOW DENIM PANTS, 25 W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1027",
         "BRAND":"ALANUI",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/LWYA026S23_DEN001_4584.jpg",
         "BUSINESSPARTNERID":"C002652",
         "BUSINESSPARTNER":"LIORA EPELSTEIN",
         "BUSINESSPARTNEREMAIL":"lioraepelsteinm@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50011",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"460",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"805",
         "SELL_OUT_PRICE":"805",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"HELENE GIAMI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003128",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"PA16951272_000_1272",
         "REFERENCE_MATERIAL":"WASHED NUDE DRILL SHORT CARGO P",
         "MATERIAL_ID":"PA16951272_000_1272_M",
         "MATERIAL":"WASHED NUDE DRILL SHORT CARGO P, M W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1046",
         "BRAND":"ANDREADAMO",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/PA16951272_000_1272.jpg",
         "BUSINESSPARTNERID":"C002652",
         "BUSINESSPARTNER":"LIORA EPELSTEIN",
         "BUSINESSPARTNEREMAIL":"lioraepelsteinm@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50011",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"260",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"509.6",
         "SELL_OUT_PRICE":"509.6",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"HELENE GIAMI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003128",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"RO01C5375_SEM1_0854",
         "REFERENCE_MATERIAL":"SHORTS RICAMATI - BOXERS - PEAR",
         "MATERIAL_ID":"RO01C5375_SEM1_0854_40",
         "MATERIAL":"SHORTS RICAMATI - BOXERS - PEAR, 40 W IT",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1469",
         "BRAND":"RICK OWENS",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/RO01C5375_SEM1_0854.jpg",
         "BUSINESSPARTNERID":"C002652",
         "BUSINESSPARTNER":"LIORA EPELSTEIN",
         "BUSINESSPARTNEREMAIL":"lioraepelsteinm@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50011",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"537",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"1015",
         "SELL_OUT_PRICE":"1015",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"HELENE GIAMI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003129",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"LWYA026S23_DEN001_4584",
         "REFERENCE_MATERIAL":"OVER THE RAINBOW DENIM PANTS",
         "MATERIAL_ID":"LWYA026S23_DEN001_4584_26",
         "MATERIAL":"OVER THE RAINBOW DENIM PANTS, 26 W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1027",
         "BRAND":"ALANUI",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/LWYA026S23_DEN001_4584.jpg",
         "BUSINESSPARTNERID":"C001038",
         "BUSINESSPARTNER":"DANIELA DANCASSAB",
         "BUSINESSPARTNEREMAIL":"dancassab@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50011",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"460",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"805",
         "SELL_OUT_PRICE":"805",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"HELENE GIAMI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003130",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"BB550VTC_000_OFFGRE",
         "REFERENCE_MATERIAL":"550",
         "MATERIAL_ID":"BB550VTC_000_OFFGRE_8",
         "MATERIAL":"550, 8 M US",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1407",
         "BRAND":"NEW BALANCE",
         "FAMILY_ID":"SHS",
         "FAMILY":"SHOES",
         "GENDER":"UNISX",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/BB550VTC_000_OFFGRE.jpg",
         "BUSINESSPARTNERID":"C002675",
         "BUSINESSPARTNER":"MARIA VITERI",
         "BUSINESSPARTNEREMAIL":"marialex_viteri@hotmail.com",
         "DOCUMENTPOSSALESPERSONID":"50012",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"85",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"170",
         "SELL_OUT_PRICE":"170",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"WAFAA KASSBI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003130",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"UTS004_726_464",
         "REFERENCE_MATERIAL":"TONAL AMI DE COEUR TSHIRT",
         "MATERIAL_ID":"UTS004_726_464_S",
         "MATERIAL":"TONAL AMI DE COEUR TSHIRT, S W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1039",
         "BRAND":"AMI PARIS",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/UTS004_726_464.jpg",
         "BUSINESSPARTNERID":"C002675",
         "BUSINESSPARTNER":"MARIA VITERI",
         "BUSINESSPARTNEREMAIL":"marialex_viteri@hotmail.com",
         "DOCUMENTPOSSALESPERSONID":"50012",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"54",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"140",
         "SELL_OUT_PRICE":"140",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"WAFAA KASSBI",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003133",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"DK25DL_000_BLACK",
         "REFERENCE_MATERIAL":"METAL BALLS EMBR WAIST & BACK C",
         "MATERIAL_ID":"DK25DL_000_BLACK_8",
         "MATERIAL":"METAL BALLS EMBR WAIST & BACK C, 8 W UK",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1662",
         "BRAND":"DAVID KOMA",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/DK25DL_000_BLACK.jpg",
         "BUSINESSPARTNERID":"C002681",
         "BUSINESSPARTNER":"STANLEY HATTAB",
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50013",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"832.2",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"1603",
         "SELL_OUT_PRICE":"1603",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"ANNE DUDA",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003134",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"236WCP128_D060_519",
         "REFERENCE_MATERIAL":"Effie' long pants",
         "MATERIAL_ID":"236WCP128_D060_519_24",
         "MATERIAL":"Effie' long pants, 24 W IN",
         "SKU_SEASON":"FW23",
         "BRAND_ID":"1534",
         "BRAND":"THE ATTICO",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/236WCP128_D060_519.jpg",
         "BUSINESSPARTNERID":null,
         "BUSINESSPARTNER":null,
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50015",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"257",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"670",
         "SELL_OUT_PRICE":"670",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"LISA FROGER",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003134",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"P120W_WOTCO004_05",
         "REFERENCE_MATERIAL":"WORKWEAR G. DYE EVERGREEN PANTS",
         "MATERIAL_ID":"P120W_WOTCO004_05_S",
         "MATERIAL":"WORKWEAR G. DYE EVERGREEN PANTS, S W IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1348",
         "BRAND":"MARINE SERRE",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"WOMAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/P120W_WOTCO004_05.jpg",
         "BUSINESSPARTNERID":null,
         "BUSINESSPARTNER":null,
         "BUSINESSPARTNEREMAIL":null,
         "DOCUMENTPOSSALESPERSONID":"50015",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"226",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"600",
         "SELL_OUT_PRICE":"600",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"LISA FROGER",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003135",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"235DE008_1015_3DF",
         "REFERENCE_MATERIAL":"DENIM SUNO",
         "MATERIAL_ID":"235DE008_1015_3DF_33",
         "MATERIAL":"DENIM SUNO, 33 M IN",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1275",
         "BRAND":"JACQUEMUS",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"MAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/235DE008_1015_3DF.jpg",
         "BUSINESSPARTNERID":"C002684",
         "BUSINESSPARTNER":"JEAN PHILIPPE GBAMIN",
         "BUSINESSPARTNEREMAIL":"jpg2595@gmail.com",
         "DOCUMENTPOSSALESPERSONID":"50013",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"140",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"370",
         "SELL_OUT_PRICE":"370",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"ANNE DUDA",
         "DOCUMENTDATESTRING":"07-06-2023"
      },
      {
         "COMPANYID":"MFR1",
         "COMPANY":"Modes France SAS",
         "DOCUMENTDATE":"/Date(1686096000000)/",
         "DOCUMENTTYPE":"RECEIPT",
         "DOCUMENTENTRY":"FR05100003136",
         "STOREID":"FR05",
         "STORE":"PARIS MODES",
         "REFERENCE_MATERIAL_ID":"T2522FBP00001_000_10000",
         "REFERENCE_MATERIAL":"TAILORED SCALLOP EDGE JACKET",
         "MATERIAL_ID":"T2522FBP00001_000_10000_52",
         "MATERIAL":"TAILORED SCALLOP EDGE JACKET, 52 M IT",
         "SKU_SEASON":"SS23",
         "BRAND_ID":"1634",
         "BRAND":"RANDOM IDENTITIES",
         "FAMILY_ID":"RTW",
         "FAMILY":"READY TO WEAR",
         "GENDER":"MAN",
         "IMAGE_URL":"https://modes-pcm.s3.eu-central-1.amazonaws.com/product-images-chalco/T2522FBP00001_000_10000.jpg",
         "BUSINESSPARTNERID":"C002688",
         "BUSINESSPARTNER":"KAIS SAADI",
         "BUSINESSPARTNEREMAIL":"saadi.kais@kheishi.com",
         "DOCUMENTPOSSALESPERSONID":"50017",
         "PIECES_SOLD":"1",
         "WHOLESALE_PRICE":"246",
         "UM_WHOLESALE_PRICE":"EUR",
         "RETAIL_FULL_PRICE":"483",
         "SELL_OUT_PRICE":"483",
         "DISCOUNT_APPLIED":"0",
         "DISCOUNT_PERCENTAGE":"0",
         "CURRENCY":"€",
         "DOCUMENTPOSSALESPERSON":"KILLIAN TAVARES",
         "DOCUMENTDATESTRING":"07-06-2023"
      }
   ]
}